---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-dev
  namespace: dev
spec:
  interval: 10m
  url: https://stefanprodan.github.io/podinfo/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
spec:
  interval: 5m
  releaseName: podinfo-dev
  chart:
    spec:
      chart: podinfo
      version: 3.1.5
      sourceRef:
        kind: HelmRepository
        name: podinfo-dev
      interval: 10m
  values:
    replicaCount: 1
