---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-manifests
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./releases
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo
