---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-prod
  namespace: prod
spec:
  interval: 10m
  url: https://stefanprodan.github.io/podinfo/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  interval: 5m
  releaseName: podinfo-prod
  chart:
    spec:
      chart: prodinfo
      tag: 0.4.12
      sourceRef:
        kind: HelmRepository
        name: podinfo-prod
      interval: 10m
  values:
    image:
      repository: bdavidsonim/podinfo
    replicaCount: 3
