---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-rc
  namespace: stg
spec:
  interval: 10m
  url: https://stefanprodan.github.io/podinfo/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  interval: 5m
  releaseName: podinfo-rc
  chart:
    spec:
      chart: podinfo
      version: 3.1.5
      sourceRef:
        kind: HelmRepository
        name: podinfo-rc
      interval: 10m
  values:
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
